version: '3'
services:
  moodle:
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - '8080:80'
    volumes:
      - moodle_data:/var/www/html
    environment:
      - MOODLE_DATABASE_TYPE=pgsql
      - MOODLE_DATABASE_HOST=db
      - MOODLE_DATABASE_PORT_NUMBER=5432
      - MOODLE_DATABASE_USER=james
      - MOODLE_DATABASE_PASSWORD=aguiaCareca
      - MOODLE_DATABASE_NAME=BaleiaAzul
    depends_on:
      - db
    networks:
      - moodle_net

  db:
    image: postgres:latest
    environment:
      - POSTGRES_PASSWORD=aguiaCareca
      - POSTGRES_DB=BaleiaAzul
      - POSTGRES_USER=james
    volumes:
      - ./db_data:/var/lib/postgresql/data
    networks:
      - moodle_net

networks:
  moodle_net:

volumes:
  moodle_data:
  db_data: